<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>HeartyHearth</Product>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="frmLogin.cs" />
    <Compile Remove="frmLogin.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="frmLogin.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CPUFramework\CPUFramework.csproj" />
    <ProjectReference Include="..\..\CPUWindowsFormFramework\CPUWindowsFormFramework.csproj" />
    <ProjectReference Include="..\RecipeSystem\RecipeSystem.csproj" />
  </ItemGroup>

</Project>